name: build

on: [push, pull_request]

jobs:
  MRI:
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11, windows-2022]
        ruby: [ '2.5', '2.6', '2.7', '3.0', '3.1', head]
        include:
          - { os: windows-2022 , ruby: mswin }
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Install
        run: |
          gem install --no-document bundler
          gem build numo-narray.gemspec
          gem install numo-narray-*.gem
          bundle install
      - name: Tests
        run: rake test

  ruby-head-debug:
    name: Build on ruby-head-debug
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'debug' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Install
        run: |
          gem install --no-document bundler
          gem build numo-narray.gemspec
          gem install numo-narray-*.gem
          bundle install
      - name: Tests
        run: rake test
